#!/usr/bin/env bash
#Write a Bash script that transfers a file from our client to a server.

#file=$1
#ip=$2
#user=$3
#key=$4

if [[ $# -lt 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [[ -s $1 ]] && [[ -f $1 ]] && [[ -s $4 ]] && [[ -f $4 ]]
	then
		scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
	elif [[ -s $1 ]] && [[ -f $1 ]]
	then
		scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
	else
		:
	fi
fi

