#!/usr/bin/env bash
#Install and Configure NGINX, Make a GET request.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
