#!/usr/bin/env bash
#Write a Bash script that displays: The content of the current directory (In a list format, where only the part of the name after the first dash is displayed.

ls | cut -d '-' -f2
